### ISSUE TITLE
ServiceManagementBundleBuilder should provide a default health manager

### ISSUE THREAD

**Issue by RichardHightower** [advantageous/reakt#37]
java.lang.NullPointerException: ServiceHealthManager must be set

```
at java.util.Objects.requireNonNull(Objects.java:228)
at io.advantageous.qbit.admin.ServiceManagementBundleBuilder.getServiceHealthManager(ServiceManagementBundleBuilder.java:117)
at io.advantageous.qbit.admin.ServiceManagementBundleBuilder.build(ServiceManagementBundleBuilder.java:167)
```

**Comment by RichardHightower** [comment]
wrong project
